# Version of Docker-compose
version: '1.0'
services:
  # Service name
  node:
    container_name: jonykarol_node
    image: jonykarol_node_image
    restart: always
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: .
      # Name of the Dockerfile
      dockerfile: Dockerfile
    ports:
        # External port:Internal port
      - 3010:3000
    # links:
    #   - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  