
pipeline {
    agent any
    parameters {
        string(name: 'name_container', defaultValue: 'booking_calendar_node', description: 'nombre del docker')
        /* string(name: 'name_imagen', defaultValue: 'booking_calendar_node_image', description: 'nombre de la imagen')
        string(name: 'tag_imagen', defaultValue: 'latest', description: 'etiqueta de la imagen')
        string(name: 'puerto_imagen', defaultValue: '3000', description: 'puerto a publicar') */
    }
    environment {
        /* name_final = "${name_container}${tag_imagen}${puerto_imagen}"         */
        name_final = "booking_calendar_node"
    }
    stages {
        /* stage('Configurar permisos de Docker') {
            steps {
                script {
                    def currentUsername = sh(script: 'whoami', returnStdout: true).trim()
                    // Cambiar el usuario de Jenkins al grupo docker
                    sh "usermod -aG docker ${currentUsername}"
                }
            }
        } */
        stage('stop/rm') {
            when {
                expression { 
                    DOCKER_EXIST = sh(returnStdout: true, script: 'echo "$(sudo docker ps -q --filter name=${name_final})"').trim()
                    return  DOCKER_EXIST != '' 
                }
            }
            steps {
                script{
                    sh ''' 
                         docker stop ${name_final}
                    '''
                }    
            }                                          
        }   
        stage('restart') {
            steps {
                script{
                    //def dockerComposeDir = sh(script: 'dirname /home/debian/bookingCalendarServer/docker-compose.yml', returnStdout: true).trim()
                    //echo "Directorio del archivo docker-compose.yml: $dockerComposeDir"
                    /* sh ''' 
                    docker build    jobs/dockerweb/ -t ${name_imagen}:${tag_imagen}
                    ''' */
                    /* sh ''' 
                    docker-compose restart node
                    ''' */
                    
                    /* sh 'docker-compose -f /home/debian/bookingCalendarServer/docker-compose.yml restart node' */
                    sh 'docker-compose -f /docker-compose/docker-compose.yml restart node'
                    
                }  
            }                                              
        }
        /* stage('run') {
            steps {
                script{
                    sh ''' 
                        docker run -dp ${puerto_imagen}:80 --name ${name_final} ${name_imagen}:${tag_imagen}
 
                    '''
                }    
            }                    
                                  
        } */
    }   
}
